<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>Veauty.CodeGen</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Unity.CompilationPipeline.Common">
      <HintPath>/Applications/Unity/Hub/Editor/6000.5.1f1/Unity.app/Contents/Resources/Scripting/Managed/Unity.CompilationPipeline.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>/Applications/Unity/Hub/Editor/6000.5.1f1/Unity.app/Contents/Resources/BuildPipeline/Compilation/ApiUpdater/Mono.Cecil.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil.Rocks">
      <HintPath>/Applications/Unity/Hub/Editor/6000.5.1f1/Unity.app/Contents/Resources/BuildPipeline/Compilation/ApiUpdater/Mono.Cecil.Rocks.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil.Pdb">
      <HintPath>/Applications/Unity/Hub/Editor/6000.5.1f1/Unity.app/Contents/Resources/BuildPipeline/Compilation/ApiUpdater/Mono.Cecil.Pdb.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ComponentGenerator.cs" />
  </ItemGroup>

</Project>
